# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hauptfenster.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmd_SetLernen = QtWidgets.QPushButton(self.centralwidget)
        self.cmd_SetLernen.setObjectName("cmd_SetLernen")
        self.horizontalLayout.addWidget(self.cmd_SetLernen)
        self.cmd_AusgewaehlteLernen = QtWidgets.QPushButton(self.centralwidget)
        self.cmd_AusgewaehlteLernen.setObjectName("cmd_AusgewaehlteLernen")
        self.horizontalLayout.addWidget(self.cmd_AusgewaehlteLernen)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.aktion = QtWidgets.QFrame(self.centralwidget)
        self.aktion.setStyleSheet("QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 6px;\n"
"    border: 1px solid #AAAAAA;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    border: 2px solid rgb(44, 76, 116);\n"
"    background-color: #EEEEEE;\n"
"}\n"
"\n"
"QFrame:focus {\n"
"    border: 4px solid #00FF00;\n"
"}\n"
"\n"
"QLabel{\n"
"    border: 0px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 0px;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.aktion.setFrameShape(QtWidgets.QFrame.Box)
        self.aktion.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.aktion.setLineWidth(1)
        self.aktion.setObjectName("aktion")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.aktion)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.aktion)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/icons/logout_FILL0_wght500_GRAD0_opsz40.svg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.aktion)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.aktion)
        self.cmd_Beenden = QtWidgets.QPushButton(self.centralwidget)
        self.cmd_Beenden.setObjectName("cmd_Beenden")
        self.horizontalLayout.addWidget(self.cmd_Beenden)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_UnterMenu = QtWidgets.QFrame(self.centralwidget)
        self.line_UnterMenu.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_UnterMenu.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_UnterMenu.setObjectName("line_UnterMenu")
        self.verticalLayout_2.addWidget(self.line_UnterMenu)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.trw_Explorer = QtWidgets.QTreeWidget(self.splitter)
        self.trw_Explorer.setStyleSheet("selection-background-color: rgb(201, 220, 225);\n"
"selection-color: rgb(0, 0, 0);")
        self.trw_Explorer.setObjectName("trw_Explorer")
        self.trw_Explorer.headerItem().setText(0, "1")
        self.tbv_Liste = QtWidgets.QTableView(self.splitter)
        self.tbv_Liste.setObjectName("tbv_Liste")
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 22))
        self.menubar.setObjectName("menubar")
        self.menuVocitrainer = QtWidgets.QMenu(self.menubar)
        self.menuVocitrainer.setObjectName("menuVocitrainer")
        self.menuLernen = QtWidgets.QMenu(self.menubar)
        self.menuLernen.setObjectName("menuLernen")
        self.menu_Extra = QtWidgets.QMenu(self.menubar)
        self.menu_Extra.setObjectName("menu_Extra")
        self.menuMarketplace = QtWidgets.QMenu(self.menubar)
        self.menuMarketplace.setObjectName("menuMarketplace")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mn_Ueber = QtWidgets.QAction(MainWindow)
        self.mn_Ueber.setObjectName("mn_Ueber")
        self.mn_NeuesSet = QtWidgets.QAction(MainWindow)
        self.mn_NeuesSet.setObjectName("mn_NeuesSet")
        self.mn_NeuerOrdner = QtWidgets.QAction(MainWindow)
        self.mn_NeuerOrdner.setObjectName("mn_NeuerOrdner")
        self.mn_Einstellungen = QtWidgets.QAction(MainWindow)
        self.mn_Einstellungen.setCheckable(False)
        self.mn_Einstellungen.setObjectName("mn_Einstellungen")
        self.mn_Herunterladen = QtWidgets.QAction(MainWindow)
        self.mn_Herunterladen.setObjectName("mn_Herunterladen")
        self.mn_Hochladen = QtWidgets.QAction(MainWindow)
        self.mn_Hochladen.setObjectName("mn_Hochladen")
        self.mn_HochgeladeneVerwalten = QtWidgets.QAction(MainWindow)
        self.mn_HochgeladeneVerwalten.setObjectName("mn_HochgeladeneVerwalten")
        self.mn_Profil = QtWidgets.QAction(MainWindow)
        self.mn_Profil.setObjectName("mn_Profil")
        self.menuVocitrainer.addAction(self.mn_NeuesSet)
        self.menuVocitrainer.addAction(self.mn_NeuerOrdner)
        self.menuVocitrainer.addSeparator()
        self.menu_Extra.addAction(self.mn_Einstellungen)
        self.menu_Extra.addAction(self.mn_Ueber)
        self.menuMarketplace.addAction(self.mn_Herunterladen)
        self.menuMarketplace.addAction(self.mn_Hochladen)
        self.menuMarketplace.addAction(self.mn_HochgeladeneVerwalten)
        self.menuMarketplace.addAction(self.mn_Profil)
        self.menubar.addAction(self.menuVocitrainer.menuAction())
        self.menubar.addAction(self.menuLernen.menuAction())
        self.menubar.addAction(self.menuMarketplace.menuAction())
        self.menubar.addAction(self.menu_Extra.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmd_SetLernen.setToolTip(_translate("MainWindow", "Dieses Set lernen"))
        self.cmd_SetLernen.setStatusTip(_translate("MainWindow", "Jetzt lernen"))
        self.cmd_SetLernen.setText(_translate("MainWindow", "Set lernen"))
        self.cmd_AusgewaehlteLernen.setText(_translate("MainWindow", "Ausgewählte lernen"))
        self.label_2.setText(_translate("MainWindow", "Aktion"))
        self.cmd_Beenden.setText(_translate("MainWindow", "Beenden"))
        self.menuVocitrainer.setTitle(_translate("MainWindow", "Vocitrainer"))
        self.menuLernen.setTitle(_translate("MainWindow", "Lernen"))
        self.menu_Extra.setTitle(_translate("MainWindow", "Extra"))
        self.menuMarketplace.setTitle(_translate("MainWindow", "Marketplace"))
        self.mn_Ueber.setText(_translate("MainWindow", "Über"))
        self.mn_NeuesSet.setText(_translate("MainWindow", "Neues Set"))
        self.mn_NeuerOrdner.setText(_translate("MainWindow", "Neuer Ordner"))
        self.mn_Einstellungen.setText(_translate("MainWindow", "Einstellungen"))
        self.mn_Herunterladen.setText(_translate("MainWindow", "Herunterladen"))
        self.mn_Hochladen.setText(_translate("MainWindow", "Hochladen"))
        self.mn_HochgeladeneVerwalten.setText(_translate("MainWindow", "Hochgeladene verwalten"))
        self.mn_Profil.setText(_translate("MainWindow", "Profil"))
