# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp_herunterladen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 528)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_titel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_titel.setFont(font)
        self.lbl_titel.setObjectName("lbl_titel")
        self.verticalLayout.addWidget(self.lbl_titel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_sprache = QtWidgets.QLabel(Dialog)
        self.lbl_sprache.setObjectName("lbl_sprache")
        self.horizontalLayout.addWidget(self.lbl_sprache)
        self.cbox_sprache = QtWidgets.QComboBox(Dialog)
        self.cbox_sprache.setObjectName("cbox_sprache")
        self.cbox_sprache.addItem("")
        self.cbox_sprache.addItem("")
        self.cbox_sprache.addItem("")
        self.cbox_sprache.addItem("")
        self.horizontalLayout.addWidget(self.cbox_sprache)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_suche = QtWidgets.QLabel(Dialog)
        self.lbl_suche.setObjectName("lbl_suche")
        self.horizontalLayout_2.addWidget(self.lbl_suche)
        self.txt_suche = QtWidgets.QLineEdit(Dialog)
        self.txt_suche.setObjectName("txt_suche")
        self.horizontalLayout_2.addWidget(self.txt_suche)
        self.cmd_refresh = QtWidgets.QPushButton(Dialog)
        self.cmd_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/icons/refresh_FILL0_wght500_GRAD0_opsz40.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmd_refresh.setIcon(icon)
        self.cmd_refresh.setFlat(False)
        self.cmd_refresh.setObjectName("cmd_refresh")
        self.horizontalLayout_2.addWidget(self.cmd_refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tbl_suche = QtWidgets.QTableWidget(Dialog)
        self.tbl_suche.setObjectName("tbl_suche")
        self.tbl_suche.setColumnCount(0)
        self.tbl_suche.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_suche)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cmd_schliessen = QtWidgets.QPushButton(Dialog)
        self.cmd_schliessen.setObjectName("cmd_schliessen")
        self.horizontalLayout_3.addWidget(self.cmd_schliessen)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_titel.setText(_translate("Dialog", "Vociset herunterladen"))
        self.lbl_sprache.setText(_translate("Dialog", "Sprache:"))
        self.cbox_sprache.setItemText(0, _translate("Dialog", "Englisch"))
        self.cbox_sprache.setItemText(1, _translate("Dialog", "Französisch"))
        self.cbox_sprache.setItemText(2, _translate("Dialog", "Spanisch"))
        self.cbox_sprache.setItemText(3, _translate("Dialog", "Italienisch"))
        self.lbl_suche.setText(_translate("Dialog", "Suche:"))
        self.cmd_schliessen.setText(_translate("Dialog", "Schliessen"))
