# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainingsfenster.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Trainingsfenster(object):
    def setupUi(self, Trainingsfenster):
        Trainingsfenster.setObjectName("Trainingsfenster")
        Trainingsfenster.resize(443, 290)
        Trainingsfenster.setLayoutDirection(QtCore.Qt.LeftToRight)
        Trainingsfenster.setStyleSheet("")
        Trainingsfenster.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Trainingsfenster)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(Trainingsfenster)
        self.stackedWidget.setObjectName("stackedWidget")
        self.frage_page = QtWidgets.QWidget()
        self.frage_page.setObjectName("frage_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frage_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f_lbl_deutsch_beschreibung = QtWidgets.QLabel(self.frage_page)
        self.f_lbl_deutsch_beschreibung.setObjectName("f_lbl_deutsch_beschreibung")
        self.verticalLayout.addWidget(self.f_lbl_deutsch_beschreibung)
        self.f_lbl_deutsch_wort = QtWidgets.QLabel(self.frage_page)
        self.f_lbl_deutsch_wort.setStyleSheet("background-color: rgb(201, 220, 225);\n"
"border: 3px solid;\n"
"border-radius: 3px;\n"
"border-color: rgb(201, 220, 225);")
        self.f_lbl_deutsch_wort.setObjectName("f_lbl_deutsch_wort")
        self.verticalLayout.addWidget(self.f_lbl_deutsch_wort)
        self.f_lbl_fremdsprache = QtWidgets.QLabel(self.frage_page)
        self.f_lbl_fremdsprache.setObjectName("f_lbl_fremdsprache")
        self.verticalLayout.addWidget(self.f_lbl_fremdsprache)
        self.f_txt_fremdsprache = QtWidgets.QLineEdit(self.frage_page)
        self.f_txt_fremdsprache.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.f_txt_fremdsprache.setObjectName("f_txt_fremdsprache")
        self.verticalLayout.addWidget(self.f_txt_fremdsprache)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.f_cmd_pruefen = QtWidgets.QPushButton(self.frage_page)
        self.f_cmd_pruefen.setObjectName("f_cmd_pruefen")
        self.horizontalLayout.addWidget(self.f_cmd_pruefen)
        self.f_cmd_abbrechen = QtWidgets.QPushButton(self.frage_page)
        self.f_cmd_abbrechen.setObjectName("f_cmd_abbrechen")
        self.horizontalLayout.addWidget(self.f_cmd_abbrechen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.frage_page)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.stackedWidget.addWidget(self.frage_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.a_lbl_deutsch_beschreibung = QtWidgets.QLabel(self.page_2)
        self.a_lbl_deutsch_beschreibung.setObjectName("a_lbl_deutsch_beschreibung")
        self.verticalLayout_2.addWidget(self.a_lbl_deutsch_beschreibung)
        self.a_lbl_deutsch_wort = QtWidgets.QLabel(self.page_2)
        self.a_lbl_deutsch_wort.setStyleSheet("background-color: rgb(201, 220, 225);\n"
"border: 3px solid;\n"
"border-radius: 3px;\n"
"border-color: rgb(201, 220, 225);")
        self.a_lbl_deutsch_wort.setObjectName("a_lbl_deutsch_wort")
        self.verticalLayout_2.addWidget(self.a_lbl_deutsch_wort)
        self.a_lbl_fremdsprache_beschreibung = QtWidgets.QLabel(self.page_2)
        self.a_lbl_fremdsprache_beschreibung.setObjectName("a_lbl_fremdsprache_beschreibung")
        self.verticalLayout_2.addWidget(self.a_lbl_fremdsprache_beschreibung)
        self.a_lbl_fremdsprache_wort = QtWidgets.QLabel(self.page_2)
        self.a_lbl_fremdsprache_wort.setStyleSheet("background-color: rgb(225, 171, 171);\n"
"border: 3px solid;\n"
"border-radius: 3px;\n"
"border-color: rgb(225, 171, 171);")
        self.a_lbl_fremdsprache_wort.setObjectName("a_lbl_fremdsprache_wort")
        self.verticalLayout_2.addWidget(self.a_lbl_fremdsprache_wort)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.a_cmd_weiter = QtWidgets.QPushButton(self.page_2)
        self.a_cmd_weiter.setObjectName("a_cmd_weiter")
        self.horizontalLayout_2.addWidget(self.a_cmd_weiter)
        self.a_cmd_abbrechen = QtWidgets.QPushButton(self.page_2)
        self.a_cmd_abbrechen.setObjectName("a_cmd_abbrechen")
        self.horizontalLayout_2.addWidget(self.a_cmd_abbrechen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)

        self.retranslateUi(Trainingsfenster)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Trainingsfenster)

    def retranslateUi(self, Trainingsfenster):
        _translate = QtCore.QCoreApplication.translate
        Trainingsfenster.setWindowTitle(_translate("Trainingsfenster", "Dialog"))
        self.f_lbl_deutsch_beschreibung.setText(_translate("Trainingsfenster", "Deutsch:"))
        self.f_lbl_deutsch_wort.setText(_translate("Trainingsfenster", "TextLabel"))
        self.f_lbl_fremdsprache.setText(_translate("Trainingsfenster", "Fremdsprache:"))
        self.f_cmd_pruefen.setText(_translate("Trainingsfenster", "Prüfen"))
        self.f_cmd_abbrechen.setText(_translate("Trainingsfenster", "Abbrechen"))
        self.label.setText(_translate("Trainingsfenster", "Frage"))
        self.a_lbl_deutsch_beschreibung.setText(_translate("Trainingsfenster", "Deutsch:"))
        self.a_lbl_deutsch_wort.setText(_translate("Trainingsfenster", "TextLabel"))
        self.a_lbl_fremdsprache_beschreibung.setText(_translate("Trainingsfenster", "Fremdsprache:"))
        self.a_lbl_fremdsprache_wort.setText(_translate("Trainingsfenster", "TextLabel"))
        self.a_cmd_weiter.setText(_translate("Trainingsfenster", "Weiter"))
        self.a_cmd_abbrechen.setText(_translate("Trainingsfenster", "Abbrechen"))
        self.label_2.setText(_translate("Trainingsfenster", "Antwort"))
