# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp_hochladen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mp_Hochladen(object):
    def setupUi(self, Mp_Hochladen):
        Mp_Hochladen.setObjectName("Mp_Hochladen")
        Mp_Hochladen.resize(504, 331)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icons/cloud_upload_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mp_Hochladen.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Mp_Hochladen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Mp_Hochladen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_name = QtWidgets.QLabel(Mp_Hochladen)
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout_2.addWidget(self.lbl_name)
        self.txt_name = QtWidgets.QLineEdit(Mp_Hochladen)
        self.txt_name.setObjectName("txt_name")
        self.horizontalLayout_2.addWidget(self.txt_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_sprache = QtWidgets.QLabel(Mp_Hochladen)
        self.lbl_sprache.setObjectName("lbl_sprache")
        self.horizontalLayout_3.addWidget(self.lbl_sprache)
        self.cmb_sprache = QtWidgets.QComboBox(Mp_Hochladen)
        self.cmb_sprache.setObjectName("cmb_sprache")
        self.cmb_sprache.addItem("")
        self.cmb_sprache.addItem("")
        self.cmb_sprache.addItem("")
        self.cmb_sprache.addItem("")
        self.cmb_sprache.addItem("")
        self.horizontalLayout_3.addWidget(self.cmb_sprache)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lbl_tags = QtWidgets.QLabel(Mp_Hochladen)
        self.lbl_tags.setObjectName("lbl_tags")
        self.verticalLayout.addWidget(self.lbl_tags)
        self.txt_tags = QtWidgets.QPlainTextEdit(Mp_Hochladen)
        self.txt_tags.setObjectName("txt_tags")
        self.verticalLayout.addWidget(self.txt_tags)
        self.label_2 = QtWidgets.QLabel(Mp_Hochladen)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmd_hochladen = QtWidgets.QPushButton(Mp_Hochladen)
        self.cmd_hochladen.setObjectName("cmd_hochladen")
        self.horizontalLayout.addWidget(self.cmd_hochladen)
        self.cmd_abbrechen = QtWidgets.QPushButton(Mp_Hochladen)
        self.cmd_abbrechen.setObjectName("cmd_abbrechen")
        self.horizontalLayout.addWidget(self.cmd_abbrechen)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Mp_Hochladen)
        QtCore.QMetaObject.connectSlotsByName(Mp_Hochladen)

    def retranslateUi(self, Mp_Hochladen):
        _translate = QtCore.QCoreApplication.translate
        Mp_Hochladen.setWindowTitle(_translate("Mp_Hochladen", "Set hochladen"))
        self.label.setText(_translate("Mp_Hochladen", "Set hochladen"))
        self.lbl_name.setText(_translate("Mp_Hochladen", "Name:"))
        self.lbl_sprache.setText(_translate("Mp_Hochladen", "Sprache:"))
        self.cmb_sprache.setItemText(0, _translate("Mp_Hochladen", "Englisch"))
        self.cmb_sprache.setItemText(1, _translate("Mp_Hochladen", "Französisch"))
        self.cmb_sprache.setItemText(2, _translate("Mp_Hochladen", "Latein"))
        self.cmb_sprache.setItemText(3, _translate("Mp_Hochladen", "Spanisch"))
        self.cmb_sprache.setItemText(4, _translate("Mp_Hochladen", "Italienisch"))
        self.lbl_tags.setText(_translate("Mp_Hochladen", "Beschreibung / Tags:"))
        self.label_2.setText(_translate("Mp_Hochladen", "Schreiben Sie hier Wörter rein, die zu dem Set passen und vereinfachen Sie damit die Suche danach."))
        self.cmd_hochladen.setText(_translate("Mp_Hochladen", "Hochladen"))
        self.cmd_abbrechen.setText(_translate("Mp_Hochladen", "Abbrechen"))
import ressources_rc
