# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'neuesWort.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NeuesWort(object):
    def setupUi(self, NeuesWort):
        NeuesWort.setObjectName("NeuesWort")
        NeuesWort.resize(553, 477)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icons/add_box_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NeuesWort.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(NeuesWort)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_deutsch = QtWidgets.QLabel(NeuesWort)
        self.lbl_deutsch.setObjectName("lbl_deutsch")
        self.verticalLayout.addWidget(self.lbl_deutsch)
        self.txt_wort = QtWidgets.QLineEdit(NeuesWort)
        self.txt_wort.setObjectName("txt_wort")
        self.verticalLayout.addWidget(self.txt_wort)
        self.lbl_fremdsprache = QtWidgets.QLabel(NeuesWort)
        self.lbl_fremdsprache.setObjectName("lbl_fremdsprache")
        self.verticalLayout.addWidget(self.lbl_fremdsprache)
        self.txt_fremdwort = QtWidgets.QLineEdit(NeuesWort)
        self.txt_fremdwort.setObjectName("txt_fremdwort")
        self.verticalLayout.addWidget(self.txt_fremdwort)
        self.lbl_definition = QtWidgets.QLabel(NeuesWort)
        self.lbl_definition.setObjectName("lbl_definition")
        self.verticalLayout.addWidget(self.lbl_definition)
        self.txt_definition = QtWidgets.QLineEdit(NeuesWort)
        self.txt_definition.setObjectName("txt_definition")
        self.verticalLayout.addWidget(self.txt_definition)
        self.lbl_bemerkung = QtWidgets.QLabel(NeuesWort)
        self.lbl_bemerkung.setObjectName("lbl_bemerkung")
        self.verticalLayout.addWidget(self.lbl_bemerkung)
        self.txt_bemerkung = QtWidgets.QLineEdit(NeuesWort)
        self.txt_bemerkung.setObjectName("txt_bemerkung")
        self.verticalLayout.addWidget(self.txt_bemerkung)
        spacerItem = QtWidgets.QSpacerItem(20, 199, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_erfolg = QtWidgets.QLabel(NeuesWort)
        self.lbl_erfolg.setStyleSheet("color: rgb(0, 85, 0);")
        self.lbl_erfolg.setObjectName("lbl_erfolg")
        self.horizontalLayout.addWidget(self.lbl_erfolg)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmd_hinzufuegen = QtWidgets.QPushButton(NeuesWort)
        self.cmd_hinzufuegen.setObjectName("cmd_hinzufuegen")
        self.horizontalLayout.addWidget(self.cmd_hinzufuegen)
        self.cmd_fertig = QtWidgets.QPushButton(NeuesWort)
        self.cmd_fertig.setObjectName("cmd_fertig")
        self.horizontalLayout.addWidget(self.cmd_fertig)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NeuesWort)
        QtCore.QMetaObject.connectSlotsByName(NeuesWort)

    def retranslateUi(self, NeuesWort):
        _translate = QtCore.QCoreApplication.translate
        NeuesWort.setWindowTitle(_translate("NeuesWort", "Wörter hinzufügen"))
        self.lbl_deutsch.setText(_translate("NeuesWort", "Deutsch:"))
        self.lbl_fremdsprache.setText(_translate("NeuesWort", "Fremdsprache:"))
        self.lbl_definition.setText(_translate("NeuesWort", "Definition:"))
        self.lbl_bemerkung.setText(_translate("NeuesWort", "Bemerkung:"))
        self.lbl_erfolg.setText(_translate("NeuesWort", "Wort hinzugefügt!"))
        self.cmd_hinzufuegen.setText(_translate("NeuesWort", "Hinzufügen"))
        self.cmd_fertig.setText(_translate("NeuesWort", "Fertig"))
import ressources_rc
