# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp_hochgeladeneVerwalten.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mp_HochgeladeneVerwalten(object):
    def setupUi(self, Mp_HochgeladeneVerwalten):
        Mp_HochgeladeneVerwalten.setObjectName("Mp_HochgeladeneVerwalten")
        Mp_HochgeladeneVerwalten.resize(527, 385)
        self.verticalLayout = QtWidgets.QVBoxLayout(Mp_HochgeladeneVerwalten)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_titel = QtWidgets.QLabel(Mp_HochgeladeneVerwalten)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_titel.setFont(font)
        self.lbl_titel.setObjectName("lbl_titel")
        self.verticalLayout.addWidget(self.lbl_titel)
        self.tbl_hochgeladeneSets = QtWidgets.QTableWidget(Mp_HochgeladeneVerwalten)
        self.tbl_hochgeladeneSets.setObjectName("tbl_hochgeladeneSets")
        self.tbl_hochgeladeneSets.setColumnCount(0)
        self.tbl_hochgeladeneSets.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_hochgeladeneSets)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmd_schliessen = QtWidgets.QPushButton(Mp_HochgeladeneVerwalten)
        self.cmd_schliessen.setObjectName("cmd_schliessen")
        self.horizontalLayout.addWidget(self.cmd_schliessen)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Mp_HochgeladeneVerwalten)
        QtCore.QMetaObject.connectSlotsByName(Mp_HochgeladeneVerwalten)

    def retranslateUi(self, Mp_HochgeladeneVerwalten):
        _translate = QtCore.QCoreApplication.translate
        Mp_HochgeladeneVerwalten.setWindowTitle(_translate("Mp_HochgeladeneVerwalten", "Hochgeladene Sets verwalten"))
        self.lbl_titel.setText(_translate("Mp_HochgeladeneVerwalten", "Hochgeladene Sets"))
        self.cmd_schliessen.setText(_translate("Mp_HochgeladeneVerwalten", "Schliessen"))
